### ISSUE TITLE
no `json` found in $PATH

### ISSUE THREAD

**Issue by mejo-** [ONLYOFFICE/ansible-role-documentserver#12]
The Debian tasks depend on a binary called `json` (provided by the [NPM json module](https://github.com/trentm/json)) in your $PATH. Running the playbook on Debian results in the `Set up ...` tasks failing du to `json` not being available.

I were able to fix this locally by running the following commands:

```
npm install -g json
ln -s /usr/local/lib/npm/bin/json /usr/local/bin/json
```

**Comment by t2d** [comment]
The json modules is included in the debian package at 
```
/var/www/onlyoffice/documentserver/npm/node_modules/.bin/json
```

**Comment by pulse-mind** [comment]
I had the same issue on Ubuntu 18

**Comment by agolybev** [comment]
Fixed by https://github.com/ONLYOFFICE/ansible-role-documentserver/pull/13
