### ISSUE TITLE
JWT settings not honored by Debian package

### ISSUE THREAD

**Issue by doobry-systemli** [ONLYOFFICE/ansible-role-documentserver#43]
Thanks for adding support to configure JWT settings in the role (in #38). Unfortunately, the tasks that configure the debconf values don't have any effect at the moment, as they're run (in [line 136-166](https://github.com/ONLYOFFICE/ansible-role-documentserver/blob/master/tasks/Debian.yml#L136-L166)) *after* the Debian package is run (in [line 93](https://github.com/ONLYOFFICE/ansible-role-documentserver/blob/master/tasks/Debian.yml#L93)).

**Comment by danilapog** [comment]
@doobry-systemli Greetings! 
Issue fixed in #59
